server:
  port: 9091

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: application.yml,static
  application:
    name: consumer-client-rest
  # 配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/springbootcloud?useSSL=false&serverTimezone=UTC
    username: root
    password: lst123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 添加 Nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

# 可选：添加 MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
